body {
    text-align: center;
    background-image: linear-gradient(darkorchid, darkmagenta, darkturquoise);
}

html {
    scroll-behavior: smooth;
}

#video {
    width: 100%;
    height: 500px;
    border: none;
}

#marqueestyle {

    background-image: linear-gradient(pink,lavender,skyblue);
    color: crimson;
    font-family: cursive;
}

.my_nav_bar {
    position: sticky;
    top: 0px;
    z-index: 99999;
}

#map iframe {
    width: 100%;
}

#Details h3 {
    display: inline;
}
